# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.cache/wt [current_project]
set_property parent.project_path /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
set_property verilog_define TOOL_VIVADO [current_fileset]
add_files /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib {
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_daisy_tx.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_daisy_test.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_daisy_rx.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/bus_clk_bridge.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/axi_slave.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/axi_master.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/bd/system/hdl/system_wrapper.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_pid.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_test.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_ps.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_hk.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_daisy.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_analog.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_ams.v
  /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/sources_1/imports/code/rtl/red_pitaya_top.v
}
read_xdc /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/constrs_1/imports/code/red_pitaya.xdc
set_property used_in_implementation false [get_files /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/constrs_1/imports/code/red_pitaya.xdc]

read_xdc /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/constrs_1/new/red_pitaya_top.xdc
set_property used_in_implementation false [get_files /home/paul/developing/workspace/RedPitaya/Paul/web-apps/m-dds-seq/src/fpga/SharedPitaya.srcs/constrs_1/new/red_pitaya_top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top red_pitaya_top -part xc7z010clg400-1 -flatten_hierarchy none -bufg 16 -keep_equivalent_registers
write_checkpoint -noxdef red_pitaya_top.dcp
catch { report_utilization -file red_pitaya_top_utilization_synth.rpt -pb red_pitaya_top_utilization_synth.pb }
